#!/bin/bash
sudo apt-get install tshark
sudo apt-get install dsniff
sudo apt-get install xterm
sudo apt-get install openssl
sudo apt-get install sslsplit
sudo apt-get install expect
red=`tput setaf 1`
sleep 2
echo ""
echo "${red}Check if error installing following packages${red}"
echo""
echo "${red}Installed all the package I think..............."
sleep 2

#touch /bin/packet-sniffer
#echo pwd > /bin/packet-sniffer



#sudo cp packets-sniff /bin/packets-sniff 
#sudo chmod +x /bin/packets-sniff

#echo "Successfully moved to bin so that you can run the script using."
